---
- name: Using Azure collection
  hosts: localhost
  tasks:
    - azure.azcollection.azure_rm_storageaccount:
        resource_group: RG-C-TEST-CIS-CIS
        name: Ansibletest
        account_type: Standard_LRS
