---
- name: Linux Deployment workbook
  hosts: all
  become: true
  vars:
    kerberos_user_password: "survey"
    AVInstallcmd: CONTROL_NODE_ID=cafba351-f032-4cd5-89c2-ce187da7b5ca bash -c "$(curl 'https://api.agent.alienvault.cloud/osquery-api/us-west-2/bootstrap?flavor=rpm')"
    
  tasks:
  - name: update all packages
    yum:
      name: "*"
      update_only: yes
      state: latest
    register: result
  
  - name: Install Realmd & samba-common-tools
    yum:
      name: 
        - realmd
        - samba-common-tools
      state: latest
    register: results
    
  - name: Copy SSSD Config to /etc/sssd
    copy:
      remote_src: yes
      src: /usr/share/doc/sssd-common/sssd-example.conf
      dest: /etc/sssd/sssd.conf
     
  - name: Join Realm
    expect:
      command: /bin/bash -c "/usr/sbin/realm join cis.ccsd.net
      responses:
        (?i)Password: "{{ kerberos_user_password }}"  
        
  - name: Realm Deny all Connections
    command: /bin/bash -c "realm deny --all"
       
  - name: Realm Allow Sys Admin Group
    command: /bin/bash -c "realm permit -g linuxadmins@cis.ccsd.net"
    
  - name: Realm Allow Operators Group
    command: /bin/bash -c "realm permit -g linux_operators@cis.ccsd.net"
       
  - name: Realm Allow Alien Vault Service Account
    command: /bin/bash -c "realm permit avservice@cis.ccsd.net"
     
  - name: Realm Allow Alien Vault Service Account
    command: /bin/bash -c "realm permit ansible@cis.ccsd.net"
    
  - name: Create sudoers file backup
    command: cp -f /etc/sudoers /etc/sudoers.backup
     
  - name: Copy suders file for safety
    command: cp -f /etc/sudoers /etc/sudoers.tmp
     
  - name: Add domain sys admins group to sudoers
    lineinfile: dest=/etc/sudoers.tmp state=present line='%cis.ccsd.net\\\linuxadmins  ALL=(ALL)       ALL'
    
  - name: Add domain operators group to sudoers
    lineinfile: dest=/etc/sudoers.tmp state=present line='%cis.ccsd.net\\\linux_operators  ALL=(ALL)       ALL'
    
  - name: Add domain alienvault service account to sudoers
    lineinfile: dest=/etc/sudoers.tmp state=present line='avservice@cis.ccsd.net ALL=(ALL)     ALL'
    
  - name: Add domain ansible service account to sudoers
    lineinfile: dest=/etc/sudoers.tmp state=present line='Ansible@cis.ccsd.net ALL=(ALL)     ALL'

  - name: Final sudoers file check
    shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
   
  - name: sssd-restart
    service:
      name: sssd
      state: restarted
    
  - name: realmd-restart
    service:
      name: realmd
      state: restarted
      
  - name: Installing / Updating Chrony
    yum:
      name: chrony
      state: latest
    register: results

  - name: Copy Chrony config to system
    copy:
      src: chrony.conf
      dest: /etc/chrony.conf
      
  - name: restart chronyd service
    service:
      name: chronyd
      state: restarted
      
  - name: Install Alien Vault using Multi Client Script
    command: /bin/bash -c  "{{ AVInstallcmd }}"
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

      
