---
- name: Linux Deployment workbook
  hosts: all
  become: true
  vars:
    kerberos_user_password: "survey"
    
  tasks:
  - name: update all packages
    yum:
      name: "*"
      update_only: yes
      state: latest
    register: result
  
  - name: Install Realmd & samba-common-tools
    yum:
      name: 
        - realmd
        - samba-common-tools
      state: latest
    register: results
    
  - name: Copy SSSD Config to /etc/sssd
    copy:
      remote_src: yes
      src: /usr/share/doc/sssd-common/sssd-example.conf
      dest: /etc/sssd/sssd.conf
     
  - name: Join Realm
    expect:
      command: /bin/bash -c "/usr/sbin/realm join cis.ccsd.net
      responses:
        (?i)Password: "{{ kerberos_user_password }}"  
        
  - name: Base Config for Realm
    expect:
      command: 
        - /bin/bash -c "realm deny --all"
        - /bin/bash -c "realm permit -g linuxadmins@cis.ccsd.net"
      
  - name: sssd-restart
    service:
      name: sssd
      state: restarted
    
  - name: realmd-restart
    service:
      name: realmd
      state: restarted
