---
- name: Package Check
  hosts: all
  become: true
  vars:
    package: "httpd"
    
  tasks:
  - name: Gather Facts
    ansible.builtin.package_facts:
      manager: auto
      
  - name: Check whether a {{ package }} is installed
    ansible.builtin.debug:
      msg: "{{ package }} {{ ansible_facts.packages[ package ][0].version }} is installed!"
    when: "package in ansible_facts.packages"
