---
- name: Package Check
  hosts: all
  become: true
  
  tasks:
  - name: update all packages
    yum:
      name: "*"
      update_only: yes
      state: latest
  
  - name: Reboot system
    ansible.builtin.reboot
      reboot_command: "init 6"
