---
- name: Package Check
  hosts: all
  become: true
  
  tasks:
  - name: update all packages
    yum:
      update_only: yes
      state: latest
      
  - name: Check for updates
    yum:
      list: updates
