---
- name: Package Check
  hosts: all
  become: true
  
  tasks:
  - name: update all packages
    yum:
      name: "*"
      update_only: yes
      state: latest
    register: result
  
  - name: Reboot system
    reboot: 
      msg: System has been rebooted by Ansible with YumUpdateAll playbook

